# Generated by Django 5.2.7 on 2025-10-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
    ]
