import React, { useState } from 'react';
import './PrivacySecurityPage.css';

const PrivacySecurityPage = () => {
  const [activeTab, setActiveTab] = useState('privacy');
  const [exportLoading, setExportLoading] = useState(false);

  const handleDataExport = async () => {
    setExportLoading(true);
    try {
      const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || 'http://localhost:8000';
      const resp = await fetch(`${API_BASE_URL}/api/accounts/data-export/`, { credentials: 'include' });
      if (!resp.ok) throw new Error('Export failed');
      const data = await resp.json();
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `my-data-export-${new Date().toISOString().split('T')[0]}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (e) {
      alert('Export failed. Please try again.');
    } finally {
      setExportLoading(false);
    }
  };

  return (
    <div className="privacy-security-container">
      <div className="privacy-header">
        <h1>Privacy & Security</h1>
        <p>Your data security and privacy are our top priorities</p>
      </div>

      <div className="tab-navigation">
        <button
          className={`tab-btn ${activeTab === 'privacy' ? 'active' : ''}`}
          onClick={() => setActiveTab('privacy')}
        >
          🔒 Privacy Policy
        </button>
        <button
          className={`tab-btn ${activeTab === 'security' ? 'active' : ''}`}
          onClick={() => setActiveTab('security')}
        >
          🛡️ Security Measures
        </button>
        <button
          className={`tab-btn ${activeTab === 'data' ? 'active' : ''}`}
          onClick={() => setActiveTab('data')}
        >
          📊 Your Data
        </button>
      </div>

      <div className="tab-content">
        {activeTab === 'privacy' && <PrivacyPolicy onDataExport={handleDataExport} exportLoading={exportLoading} />}
        {activeTab === 'security' && <SecurityMeasures />}
        {activeTab === 'data' && <YourData onDataExport={handleDataExport} exportLoading={exportLoading} />}
      </div>

      <div className="trust-badges">
        <div className="badge">
          <span className="badge-icon">🔐</span>
          <h3>256-bit Encryption</h3>
          <p>Bank-level security</p>
        </div>
        <div className="badge">
          <span className="badge-icon">✅</span>
          <h3>GDPR Compliant</h3>
          <p>Your rights protected</p>
        </div>
        <div className="badge">
          <span className="badge-icon">💳</span>
          <h3>PCI Compliant</h3>
          <p>Secure payments via Stripe</p>
        </div>
        <div className="badge">
          <span className="badge-icon">🔄</span>
          <h3>Daily Backups</h3>
          <p>Never lose your data</p>
        </div>
      </div>
    </div>
  );
};

const PrivacyPolicy = ({ onDataExport, exportLoading }) => (
  <div className="content-section">
    <h2>Privacy Policy</h2>
    <p className="last-updated">Last updated: April 12, 2026</p>

    <section className="policy-section">
      <h3>📋 What Data We Collect</h3>
      <div className="data-table">
        <table>
          <thead>
            <tr>
              <th>Data Type</th>
              <th>Purpose</th>
              <th>Required?</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>Email address</strong></td>
              <td>Account login, notifications</td>
              <td>✅ Required</td>
            </tr>
            <tr>
              <td><strong>Username</strong></td>
              <td>Account identification</td>
              <td>✅ Required</td>
            </tr>
            <tr>
              <td><strong>Name</strong></td>
              <td>Personalization, billing</td>
              <td>⚪ Optional</td>
            </tr>
            <tr>
              <td><strong>Password</strong></td>
              <td>Secure authentication</td>
              <td>✅ Required</td>
            </tr>
            <tr>
              <td><strong>Audio files</strong></td>
              <td>Provide transcription services</td>
              <td>When using service</td>
            </tr>
            <tr>
              <td><strong>Transcription text</strong></td>
              <td>Store your processed data</td>
              <td>Generated by service</td>
            </tr>
            <tr>
              <td><strong>Usage analytics</strong></td>
              <td>Improve our service</td>
              <td>Automatically collected</td>
            </tr>
            <tr>
              <td><strong>Payment information</strong></td>
              <td>Process subscriptions</td>
              <td>If subscribing</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <section className="policy-section">
      <h3>🎯 How We Use Your Data</h3>
      <ul className="feature-list">
        <li>
          <span className="check">✓</span>
          <strong>Provide Services:</strong> Process audio files, generate transcriptions, detect duplicates
        </li>
        <li>
          <span className="check">✓</span>
          <strong>Account Management:</strong> Create and maintain your account, send important updates
        </li>
        <li>
          <span className="check">✓</span>
          <strong>Billing:</strong> Process payments, send invoices (via Stripe)
        </li>
        <li>
          <span className="check">✓</span>
          <strong>Improve Services:</strong> Analyze usage patterns to enhance features
        </li>
        <li>
          <span className="check">✓</span>
          <strong>Customer Support:</strong> Respond to your questions and resolve issues
        </li>
        <li>
          <span className="cross">✗</span>
          <strong>We NEVER:</strong> Sell your data to third parties
        </li>
        <li>
          <span className="cross">✗</span>
          <strong>We NEVER:</strong> Share your audio content without permission
        </li>
        <li>
          <span className="cross">✗</span>
          <strong>We NEVER:</strong> Use your data for advertising
        </li>
      </ul>
    </section>

    <section className="policy-section">
      <h3>🔐 How We Protect Your Data</h3>
      <div className="protection-grid">
        <div className="protection-card">
          <h4>🔒 Encryption</h4>
          <p>All data transmitted using TLS 1.3 encryption (same as banking websites)</p>
        </div>
        <div className="protection-card">
          <h4>🛡️ Secure Storage</h4>
          <p>Data stored on secure servers with restricted access</p>
        </div>
        <div className="protection-card">
          <h4>🔑 Password Hashing</h4>
          <p>Passwords hashed with PBKDF2-SHA256 (600,000 iterations)</p>
        </div>
        <div className="protection-card">
          <h4>🚫 No Plain Text</h4>
          <p>We never store passwords or credit cards in plain text</p>
        </div>
      </div>
    </section>

    <section className="policy-section">
      <h3>🌍 Your Rights (GDPR)</h3>
      <div className="rights-list">
        <div className="right-item">
          <h4>📥 Right to Access</h4>
          <p>You can request a copy of all your data at any time</p>
          <button className="action-btn" onClick={onDataExport} disabled={exportLoading}>
            {exportLoading ? 'Downloading...' : 'Request My Data'}
          </button>
        </div>
        <div className="right-item">
          <h4>✏️ Right to Rectification</h4>
          <p>Update your information anytime from your profile page</p>
          <button className="action-btn">Edit Profile</button>
        </div>
        <div className="right-item">
          <h4>🗑️ Right to Deletion</h4>
          <p>Delete your account and all associated data permanently</p>
          <button className="action-btn danger">Delete Account</button>
        </div>
        <div className="right-item">
          <h4>📤 Right to Portability</h4>
          <p>Export your data in a standard format</p>
          <button className="action-btn" onClick={onDataExport} disabled={exportLoading}>
            {exportLoading ? 'Downloading...' : 'Export Data'}
          </button>
        </div>
      </div>
    </section>

    <section className="policy-section">
      <h3>🍪 Cookies & Tracking</h3>
      <p>We use minimal cookies:</p>
      <ul>
        <li><strong>Essential cookies:</strong> Required for login and authentication (cannot be disabled)</li>
        <li><strong>Analytics cookies:</strong> Help us understand usage patterns (you can opt-out)</li>
        <li><strong>Preference cookies:</strong> Remember your settings</li>
      </ul>
      <p>We do NOT use:</p>
      <ul>
        <li>❌ Advertising cookies</li>
        <li>❌ Third-party tracking pixels</li>
        <li>❌ Social media tracking</li>
      </ul>
    </section>

    <section className="policy-section">
      <h3>🤝 Third-Party Services</h3>
      <p>We share data only with trusted partners who help us provide services:</p>
      <ul>
        <li><strong>Stripe:</strong> Payment processing (PCI-compliant, they never share card details with us)</li>
        <li><strong>Anthropic:</strong> AI-powered transcription and duplicate detection (audio sent temporarily for processing)</li>
        <li><strong>AWS/Digital Ocean:</strong> Cloud hosting (data stored on secure servers)</li>
      </ul>
    </section>

    <section className="policy-section">
      <h3>⏱️ Data Retention</h3>
      <table>
        <thead>
          <tr>
            <th>Data Type</th>
            <th>Retention Period</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Account information</td>
            <td>Until account deletion</td>
          </tr>
          <tr>
            <td>Audio files & transcriptions</td>
            <td>Until project deletion or account deletion</td>
          </tr>
          <tr>
            <td>Billing records</td>
            <td>7 years (legal requirement)</td>
          </tr>
          <tr>
            <td>Usage logs</td>
            <td>90 days</td>
          </tr>
          <tr>
            <td>Backup data</td>
            <td>30 days after deletion</td>
          </tr>
        </tbody>
      </table>
    </section>

    <section className="policy-section">
      <h3>📞 Contact Us</h3>
      <p>Questions about privacy? Contact us:</p>
      <ul>
        <li>📧 Email: <a href="mailto:privacy@precisepouchtrack.com">privacy@precisepouchtrack.com</a></li>
        <li>📬 Address: [Your Business Address]</li>
        <li>⏰ Response time: Within 72 hours</li>
      </ul>
    </section>
  </div>
);

const SecurityMeasures = () => (
  <div className="content-section">
    <h2>🛡️ Security Measures</h2>
    <p className="subtitle">Multiple layers of protection keep your data safe</p>

    <section className="security-section">
      <h3>🔐 Authentication & Access Control</h3>
      <div className="security-features">
        <div className="feature-card">
          <span className="feature-icon">🔑</span>
          <h4>Password Security</h4>
          <ul>
            <li>Minimum 8 characters required</li>
            <li>Passwords hashed with PBKDF2-SHA256</li>
            <li>600,000 hashing iterations</li>
            <li>Never stored in plain text</li>
            <li>Protected against common passwords</li>
          </ul>
        </div>

        <div className="feature-card">
          <span className="feature-icon">🎫</span>
          <h4>Token Authentication</h4>
          <ul>
            <li>Secure token-based API access</li>
            <li>Tokens expire after 30 days</li>
            <li>HttpOnly cookies (XSS protection)</li>
            <li>Automatic refresh on expiry</li>
            <li>Revoked on logout</li>
          </ul>
        </div>

        <div className="feature-card">
          <span className="feature-icon">🚦</span>
          <h4>Rate Limiting</h4>
          <ul>
            <li>Login: 10 attempts per hour</li>
            <li>API: 1000 requests per hour</li>
            <li>File uploads: 50 per hour</li>
            <li>AI processing: 10 per hour</li>
            <li>Prevents brute-force attacks</li>
          </ul>
        </div>
      </div>
    </section>

    <section className="security-section">
      <h3>🔒 Data Encryption</h3>
      <div className="encryption-info">
        <div className="encryption-card">
          <h4>🌐 In Transit (TLS 1.3)</h4>
          <p>All data transmitted between your browser and our servers is encrypted using:</p>
          <ul>
            <li>✅ TLS 1.3 protocol (latest standard)</li>
            <li>✅ 256-bit AES encryption</li>
            <li>✅ Perfect Forward Secrecy</li>
            <li>✅ Valid SSL certificate</li>
          </ul>
        </div>

        <div className="encryption-card">
          <h4>💾 At Rest</h4>
          <p>Data stored on our servers is protected by:</p>
          <ul>
            <li>✅ Encrypted database connections</li>
            <li>✅ Secure server configuration</li>
            <li>✅ Restricted file permissions</li>
            <li>✅ Isolated user data</li>
          </ul>
        </div>
      </div>
    </section>

    <section className="security-section">
      <h3>💳 Payment Security</h3>
      <div className="payment-security">
        <div className="stripe-info">
          <img src="/stripe-logo.png" alt="Stripe" style={{ width: '120px', marginBottom: '15px' }} />
          <h4>PCI-DSS Level 1 Certified</h4>
          <p>We use <strong>Stripe</strong> for all payment processing. This means:</p>
          <ul>
            <li>✅ We NEVER see or store your credit card number</li>
            <li>✅ We NEVER see or store your CVV code</li>
            <li>✅ All payment data is stored securely by Stripe</li>
            <li>✅ PCI-compliant infrastructure</li>
            <li>✅ Fraud detection built-in</li>
            <li>✅ 3D Secure authentication supported</li>
          </ul>
          <p className="note">
            <strong>Note:</strong> Stripe is used by millions of businesses worldwide including
            Amazon, Google, and Spotify.
          </p>
        </div>
      </div>
    </section>

    <section className="security-section">
      <h3>🛡️ Infrastructure Security</h3>
      <div className="infrastructure-grid">
        <div className="infra-card">
          <h4>🏢 Hosting</h4>
          <ul>
            <li>Secure data centers</li>
            <li>24/7 monitoring</li>
            <li>DDoS protection</li>
            <li>Regular security audits</li>
          </ul>
        </div>

        <div className="infra-card">
          <h4>🔄 Backups</h4>
          <ul>
            <li>Daily automated backups</li>
            <li>Encrypted backup storage</li>
            <li>30-day retention</li>
            <li>Tested recovery process</li>
          </ul>
        </div>

        <div className="infra-card">
          <h4>🔥 Firewall</h4>
          <ul>
            <li>Web application firewall (WAF)</li>
            <li>IP whitelisting for admin</li>
            <li>SQL injection protection</li>
            <li>XSS attack prevention</li>
          </ul>
        </div>

        <div className="infra-card">
          <h4>📊 Monitoring</h4>
          <ul>
            <li>Real-time threat detection</li>
            <li>Security event logging</li>
            <li>Unusual activity alerts</li>
            <li>Incident response plan</li>
          </ul>
        </div>
      </div>
    </section>

    <section className="security-section">
      <h3>🔍 Code Security</h3>
      <ul className="feature-list">
        <li><span className="check">✓</span> Regular security audits</li>
        <li><span className="check">✓</span> Dependency vulnerability scanning</li>
        <li><span className="check">✓</span> Secure coding practices</li>
        <li><span className="check">✓</span> OWASP Top 10 compliance</li>
        <li><span className="check">✓</span> Input validation & sanitization</li>
        <li><span className="check">✓</span> CSRF protection</li>
        <li><span className="check">✓</span> Clickjacking prevention</li>
        <li><span className="check">✓</span> Content Security Policy (CSP)</li>
      </ul>
    </section>

    <section className="security-section">
      <h3>🚨 Incident Response</h3>
      <p>If a security incident occurs:</p>
      <ol>
        <li><strong>Detection:</strong> Our monitoring systems alert us immediately</li>
        <li><strong>Containment:</strong> We isolate affected systems within minutes</li>
        <li><strong>Investigation:</strong> Our team investigates the cause and scope</li>
        <li><strong>Notification:</strong> We notify affected users within 72 hours (GDPR requirement)</li>
        <li><strong>Resolution:</strong> We patch vulnerabilities and restore normal operations</li>
        <li><strong>Review:</strong> We analyze the incident and improve our defenses</li>
      </ol>
    </section>

    <section className="security-section">
      <h3>📢 Report a Vulnerability</h3>
      <div className="report-box">
        <p>Found a security issue? We appreciate responsible disclosure.</p>
        <p><strong>Contact:</strong> <a href="mailto:security@precisepouchtrack.com">security@precisepouchtrack.com</a></p>
        <p className="note">
          We aim to acknowledge reports within 24 hours and provide updates within 7 days.
          We may offer bug bounties for valid vulnerabilities.
        </p>
      </div>
    </section>
  </div>
);

const YourData = ({ onDataExport, exportLoading }) => (
  <div className="content-section">
    <h2>📊 Your Data</h2>
    <p className="subtitle">Complete transparency about what we collect and how it's stored</p>

    <section className="data-section">
      <h3>🗂️ Data We Store</h3>
      <div className="data-storage-table">
        <table>
          <thead>
            <tr>
              <th>Data Type</th>
              <th>Storage Location</th>
              <th>Encryption</th>
              <th>Access</th>
              <th>Retention</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>Account Details</strong><br/>(username, email, name)</td>
              <td>PostgreSQL Database</td>
              <td>TLS in transit</td>
              <td>You only</td>
              <td>Until deletion</td>
            </tr>
            <tr>
              <td><strong>Password</strong></td>
              <td>PostgreSQL Database</td>
              <td>Hashed (PBKDF2)</td>
              <td>Not even we can see it</td>
              <td>Until changed/deleted</td>
            </tr>
            <tr>
              <td><strong>Audio Files</strong></td>
              <td>Secure server filesystem</td>
              <td>TLS in transit</td>
              <td>You only</td>
              <td>Until project deleted</td>
            </tr>
            <tr>
              <td><strong>Transcriptions</strong></td>
              <td>PostgreSQL Database</td>
              <td>TLS in transit</td>
              <td>You only</td>
              <td>Until project deleted</td>
            </tr>
            <tr>
              <td><strong>Payment Info</strong></td>
              <td>Stripe servers (not ours)</td>
              <td>PCI-compliant</td>
              <td>Stripe only</td>
              <td>Per Stripe policy</td>
            </tr>
            <tr>
              <td><strong>Session Tokens</strong></td>
              <td>Browser cookies</td>
              <td>HttpOnly, Secure</td>
              <td>Your browser</td>
              <td>30 days</td>
            </tr>
            <tr>
              <td><strong>Activity Logs</strong></td>
              <td>Server log files</td>
              <td>None</td>
              <td>Admins only</td>
              <td>90 days</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <section className="data-section">
      <h3>🔒 Data We Do NOT Collect</h3>
      <ul className="feature-list">
        <li><span className="cross">✗</span> Credit card numbers (handled by Stripe)</li>
        <li><span className="cross">✗</span> CVV codes</li>
        <li><span className="cross">✗</span> Social Security Numbers</li>
        <li><span className="cross">✗</span> Biometric data</li>
        <li><span className="cross">✗</span> Location tracking</li>
        <li><span className="cross">✗</span> Device fingerprinting</li>
        <li><span className="cross">✗</span> Browsing history</li>
        <li><span className="cross">✗</span> Third-party cookies</li>
      </ul>
    </section>

    <section className="data-section">
      <h3>🔐 Who Has Access to Your Data?</h3>
      <div className="access-grid">
        <div className="access-card">
          <h4>✅ You</h4>
          <p>Full access to all your data via your account dashboard</p>
        </div>
        <div className="access-card">
          <h4>⚙️ Our Systems</h4>
          <p>Automated processing for transcription and duplicate detection</p>
        </div>
        <div className="access-card">
          <h4>👨‍💼 Support Team</h4>
          <p>Limited access only when you request help (with your permission)</p>
        </div>
        <div className="access-card">
          <h4>🤖 AI Services</h4>
          <p>Anthropic receives audio temporarily for AI processing, then it's deleted</p>
        </div>
        <div className="access-card">
          <h4>❌ Third Parties</h4>
          <p>No access. We never sell or share your data.</p>
        </div>
        <div className="access-card">
          <h4>❌ Advertisers</h4>
          <p>No access. We don't show ads or share data with ad networks.</p>
        </div>
      </div>
    </section>

    <section className="data-section">
      <h3>🗑️ Delete Your Data</h3>
      <div className="deletion-info">
        <p>You can delete your data at any time:</p>
        
        <div className="deletion-options">
          <div className="deletion-option">
            <h4>Delete Individual Projects</h4>
            <p>Go to Projects → Select → Delete</p>
            <ul>
              <li>Audio files deleted immediately</li>
              <li>Transcriptions deleted immediately</li>
              <li>Removed from backups after 30 days</li>
            </ul>
          </div>

          <div className="deletion-option">
            <h4>Delete Entire Account</h4>
            <p>Settings → Account → Delete Account</p>
            <ul>
              <li>All data deleted within 24 hours</li>
              <li>Billing records retained 7 years (legal requirement)</li>
              <li>Removed from backups after 30 days</li>
              <li><strong>Cannot be undone!</strong></li>
            </ul>
          </div>
        </div>

        <button className="danger-btn">Permanently Delete My Account</button>
      </div>
    </section>

    <section className="data-section">
      <h3>📥 Export Your Data</h3>
      <p>Request a complete export of all your data in machine-readable format (JSON):</p>
      <button className="action-btn" onClick={onDataExport} disabled={exportLoading}>
        {exportLoading ? 'Downloading...' : 'Request Data Export'}
      </button>
      <p className="note">Export includes: Account info, projects, audio metadata, transcriptions, and usage history. Your download will start immediately.</p>
    </section>

    <section className="data-section">
      <h3>🌍 International Data Transfers</h3>
      <p>Your data is stored in [Your Server Region]. If you access our service from outside this region, your data may be transferred internationally. We ensure all transfers comply with GDPR and other applicable data protection laws.</p>
    </section>
  </div>
);

export default PrivacySecurityPage;
