"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, json, logging.handlers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

# Require SECRET_KEY - no default for security
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is required. "
        "Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for security
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# AI API Configuration
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
if not OPENAI_API_KEY:
    import warnings
    warnings.warn(
        "OPENAI_API_KEY not configured. Set OPENAI_API_KEY environment variable to enable OpenAI features."
    )

# Anthropic API Configuration (for AI-powered duplicate detection)
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')
if not ANTHROPIC_API_KEY:
    import warnings
    warnings.warn(
        "ANTHROPIC_API_KEY not configured. Set ANTHROPIC_API_KEY environment variable to enable AI duplicate detection."
    )

# AI Settings
AI_PROVIDER = os.getenv('AI_PROVIDER', 'anthropic')  # 'anthropic' or 'openai'
AI_MODEL = os.getenv('AI_MODEL', 'claude-3-5-sonnet-20241022')
AI_MAX_TOKENS = int(os.getenv('AI_MAX_TOKENS', '4096'))
AI_COST_LIMIT_PER_USER_PER_MONTH = float(os.getenv('AI_COST_LIMIT_PER_USER_PER_MONTH', '50.00'))

AI_SETTINGS = {
    'PROVIDER': AI_PROVIDER,
    'MODEL': AI_MODEL,
    'MAX_TOKENS': AI_MAX_TOKENS,
    'COST_LIMIT_PER_USER_PER_MONTH': AI_COST_LIMIT_PER_USER_PER_MONTH,
    'ANTHROPIC_API_KEY': ANTHROPIC_API_KEY,
    'OPENAI_API_KEY': OPENAI_API_KEY,
}

# Read ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Tell Django it is behind an HTTPS reverse proxy (nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',      # Add CORS headers
    'rest_framework',   # DRF for API
    'rest_framework.authtoken',  # Token authentication
    'audioDiagnostic',  # Main app
    'accounts',         # User management and billing
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add CORS middleware first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Add or update these settings:
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Dynamic Redis host based on environment
def get_redis_host():
    """Get the appropriate Redis host based on environment"""
    import os
    is_docker = os.path.exists('/.dockerenv') or os.environ.get('CONTAINER_ENV') == 'true'
    return 'redis' if is_docker else 'localhost'

REDIS_HOST = get_redis_host()
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:6379/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'

# Celery Configuration for Memory-Constrained Servers
CELERY_WORKER_CONCURRENCY = 1  # Process one transcription at a time (memory-limited)
CELERY_WORKER_MAX_TASKS_PER_CHILD = 3  # Restart worker after 3 tasks (prevents memory leaks)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Don't prefetch tasks (process one at a time)
CELERY_TASK_TIME_LIMIT = 7200  # 2 hour maximum per task (hard limit)
CELERY_TASK_SOFT_TIME_LIMIT = 6900  # 1h 55m soft limit (warning before hard limit)
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion (prevents loss on crash)
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue if worker dies

# Task routing: separate queues for different workload types
CELERY_TASK_ROUTES = {
    'audioDiagnostic.tasks.transcription_tasks.*': {'queue': 'transcription'},
    'audioDiagnostic.tasks.duplicate_tasks.*': {'queue': 'processing'},
    # PDF and light tasks can use default queue
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.ExpiringTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Rate limiting to prevent abuse
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',           # Anonymous users: 100 requests per hour
        'user': '1000/hour',          # Authenticated users: 1000 requests per hour
        'upload': '50/hour',          # File uploads: 50 per hour
        'transcribe': '10/hour',      # Transcription tasks: 10 per hour (expensive)
        'process': '20/hour',         # Processing tasks: 20 per hour
        'login_burst': '5/minute',    # Login: max 5 attempts per minute per IP
        'login_sustained': '20/hour', # Login: max 20 attempts per hour per IP
        'register': '3/hour',         # Registration: max 3 new accounts per hour per IP
    }
}

# CORS Configuration
# Read allowed origins from environment (comma-separated) or fall back to dev defaults
_cors_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = (
    [o.strip() for o in _cors_env.split(',') if o.strip()]
    or [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
)
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DATABASE_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DATABASE_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.getenv('DATABASE_USER', ''),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
        'HOST': os.getenv('DATABASE_HOST', ''),
        'PORT': os.getenv('DATABASE_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'security.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'audioDiagnostic.tasks': {
            'handlers': ['debug_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['debug_file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'security': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['debug_file', 'error_file'],
        'level': 'WARNING',
    },
}

# CORS settings for frontend communication — origins controlled by first CORS block above
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only True in development (DEBUG=True)

# Allow specific headers for file uploads
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Authentication settings - merged with main REST_FRAMEWORK config above

# Stripe configuration
import os
from dotenv import load_dotenv
load_dotenv()

# Stripe configuration - require environment variables for security
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# Validate Stripe keys if billing features are enabled
if not all([STRIPE_PUBLISHABLE_KEY, STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET]):
    import warnings
    warnings.warn(
        "Stripe keys not configured. Set STRIPE_PUBLISHABLE_KEY, STRIPE_SECRET_KEY, "
        "and STRIPE_WEBHOOK_SECRET environment variables to enable billing features."
    )

# Token expiry: tokens older than this many days are rejected and the user must re-login
TOKEN_EXPIRY_DAYS = int(os.getenv('TOKEN_EXPIRY_DAYS', '30'))

# Email configuration (for user registration emails)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Development - prints to console
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Production
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Site configuration
SITE_URL = os.getenv('SITE_URL', 'http://localhost:3000')
SITE_NAME = 'Audio Duplicate Detection'

# Trial period settings
FREE_TRIAL_DAYS = 7
DEFAULT_CURRENCY = 'GBP'
DEFAULT_PLAN_LIMITS = {
    'free': {
        'max_projects_per_month': 0,  # Trial uses only
        'max_audio_duration_minutes': 60,
        'max_file_size_mb': 100,
        'max_storage_gb': 1.0,
    }
}

# Security Settings for Production SaaS
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HTTPS and Security Headers (enable in production)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# CSRF Security
CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = True

# Content Security Policy (for production)
if not DEBUG:
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
