# Generated by Django 5.2.7 on 2025-10-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioproject',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='audioproject',
            name='processed_audio',
        ),
        migrations.RemoveField(
            model_name='audioproject',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='transcriptionsegment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='transcriptionword',
            name='project',
        ),
        migrations.AddField(
            model_name='audioproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='total_chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='audio/')),
                ('processed_audio', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_section_matched', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('chapter_number', models.IntegerField(blank=True, null=True)),
                ('section_number', models.IntegerField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('processing_duration', models.FloatField(blank=True, null=True)),
                ('original_duration', models.FloatField(blank=True, null=True)),
                ('duplicates_removed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='audioDiagnostic.audioproject')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
                'unique_together': {('project', 'order_index')},
            },
        ),
        migrations.AddField(
            model_name='transcriptionsegment',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audioDiagnostic.audiofile'),
        ),
        migrations.AddField(
            model_name='transcriptionword',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='audioDiagnostic.audiofile'),
        ),
    ]
