# Generated by Django 5.2.7 on 2025-10-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0002_remove_audioproject_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
