# Generated by Django 5.2.7 on 2025-10-12 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0003_alter_audiofile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioproject',
            old_name='pdf_section_matched',
            new_name='combined_transcript',
        ),
        migrations.RenameField(
            model_name='audioproject',
            old_name='transcript_text',
            new_name='missing_content',
        ),
        migrations.RenameField(
            model_name='transcriptionsegment',
            old_name='is_pdf_match',
            new_name='pdf_match_found',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='duplicates_removed_count',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='pdf_section_matched',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='processed_audio',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='processing_duration',
        ),
        migrations.AddField(
            model_name='audioproject',
            name='final_processed_audio',
            field=models.FileField(blank=True, null=True, upload_to='assembled/'),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='pdf_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='processing_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='total_duplicates_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transcriptionsegment',
            name='duplicate_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionsegment',
            name='duplicate_type',
            field=models.CharField(choices=[('word', 'Word Repetition'), ('sentence', 'Sentence Repetition'), ('paragraph', 'Paragraph Repetition'), ('none', 'Not a Duplicate')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='transcriptionsegment',
            name='is_kept',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transcriptionsegment',
            name='pdf_match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='audioproject',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('uploading', 'Uploading Audio'), ('ready', 'Ready to Transcribe'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='setup', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_segments_processed', models.IntegerField(default=0)),
                ('duplicates_removed', models.IntegerField(default=0)),
                ('words_removed', models.IntegerField(default=0)),
                ('sentences_removed', models.IntegerField(default=0)),
                ('paragraphs_removed', models.IntegerField(default=0)),
                ('original_total_duration', models.FloatField(default=0)),
                ('final_duration', models.FloatField(default=0)),
                ('time_saved', models.FloatField(default=0)),
                ('pdf_coverage_percentage', models.FloatField(blank=True, null=True)),
                ('missing_content_count', models.IntegerField(default=0)),
                ('processing_log', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_result', to='audioDiagnostic.audioproject')),
            ],
        ),
    ]
