# Generated by Django 5.2.7 on 2025-10-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0004_rename_pdf_section_matched_audioproject_combined_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioproject',
            name='duplicates_confirmed_for_deletion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='duplicates_detected',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='duplicates_detection_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='pdf_chapter_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='pdf_match_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='pdf_match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='pdf_matched_section',
            field=models.TextField(blank=True, null=True),
        ),
    ]
