# Generated by Django 5.2.7 on 2025-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0005_audioproject_duplicates_confirmed_for_deletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioproject',
            name='pdf_match_end_char',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='pdf_match_start_char',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
