# Generated by Django 5.2.7 on 2025-10-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0006_audioproject_pdf_match_end_char_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioproject',
            name='clean_audio_transcribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='verification_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='verification_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionsegment',
            name='is_verification',
            field=models.BooleanField(default=False),
        ),
    ]
