# Generated by Django 5.2.7 on 2025-10-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0007_audioproject_clean_audio_transcribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioproject',
            name='pdf_validation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='pdf_validation_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='pdf_validation_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
