# Generated by Django 5.2.7 on 2025-10-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0008_audioproject_pdf_validation_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioproject',
            name='duration_deleted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='final_audio_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioproject',
            name='original_audio_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
