# Generated by Django 5.2.1 on 2025-12-14 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0010_audioproject_iteration_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['project', 'status'], name='audioDiagno_project_15d94a_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['project', 'order_index'], name='audioDiagno_project_51493a_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['status'], name='audioDiagno_status_ae0c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='audioproject',
            index=models.Index(fields=['user', 'status'], name='audioDiagno_user_id_df0d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='audioproject',
            index=models.Index(fields=['user', '-created_at'], name='audioDiagno_user_id_e31ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='audioproject',
            index=models.Index(fields=['status', '-created_at'], name='audioDiagno_status_fe3e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='audioproject',
            index=models.Index(fields=['parent_project'], name='audioDiagno_parent__91958d_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionsegment',
            index=models.Index(fields=['audio_file', 'segment_index'], name='audioDiagno_audio_f_157783_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionsegment',
            index=models.Index(fields=['audio_file', 'start_time'], name='audioDiagno_audio_f_bf38f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionsegment',
            index=models.Index(fields=['duplicate_group_id'], name='audioDiagno_duplica_507ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionsegment',
            index=models.Index(fields=['is_duplicate'], name='audioDiagno_is_dupl_f30e78_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionword',
            index=models.Index(fields=['segment', 'word_index'], name='audioDiagno_segment_56938c_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionword',
            index=models.Index(fields=['audio_file', 'start_time'], name='audioDiagno_audio_f_cde090_idx'),
        ),
    ]
