# Generated by Django 5.2.1 on 2025-12-20 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0011_audiofile_audiodiagno_project_15d94a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='processed_audio',
            field=models.FileField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_pdf_section', models.TextField(blank=True, null=True)),
                ('pdf_start_page', models.IntegerField(blank=True, null=True)),
                ('pdf_end_page', models.IntegerField(blank=True, null=True)),
                ('pdf_match_percentage', models.FloatField(blank=True, null=True)),
                ('pdf_match_confidence', models.FloatField(blank=True, null=True)),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='audioDiagnostic.audiofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transcriptionsegment',
            name='transcription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audioDiagnostic.transcription'),
        ),
        migrations.CreateModel(
            name='DuplicateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100)),
                ('duplicate_text', models.TextField()),
                ('occurrence_count', models.IntegerField()),
                ('total_duration_seconds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_groups', to='audioDiagnostic.audiofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audio_file', 'group_id'], name='audioDiagno_audio_f_00a7a0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['audio_file'], name='audioDiagno_audio_f_8b94da_idx'),
        ),
    ]
