# Generated by Django 5.2.1 on 2025-12-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0012_audiofile_duration_seconds_audiofile_file_size_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='processed_duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
