# Generated by Django 5.2.1 on 2025-12-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0013_audiofile_processed_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='preview_audio',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='preview_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='preview_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='preview_status',
            field=models.CharField(choices=[('none', 'None'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
    ]
