# Generated by Django 5.2.1 on 2025-12-21 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0014_add_preview_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='comparison_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='comparison_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='comparison_status',
            field=models.CharField(choices=[('none', 'Not Compared'), ('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
