# Generated by Django 5.2.1 on 2025-12-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0015_add_comparison_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='pdf_comparison_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='pdf_comparison_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='pdf_ignored_sections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
