# Generated by Django 5.2.1 on 2026-02-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioDiagnostic', '0016_audiofile_pdf_comparison_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='retranscription_status',
            field=models.CharField(choices=[('none', 'Not Re-transcribed'), ('pending', 'Re-transcription Pending'), ('processing', 'Re-transcribing'), ('completed', 'Re-transcribed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='retranscription_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='transcript_adjusted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='transcript_source',
            field=models.CharField(choices=[('none', 'None'), ('original', 'Original Whisper'), ('adjusted', 'Adjusted Preview'), ('retranscribed', 'Re-transcribed')], default='none', max_length=20),
        ),
    ]
